### PR TITLE
bugfix, indicator is only a string containing the container id

### PR DESCRIPTION
**Pull request by markusstoll**

### CODE REVIEW

**Comment by markusstoll** [comment]
I dont see any errors in the travis log - and from reviewing the change I cannot see what could be a problem with it... any hints?

**Comment by fbarthez** [comment]
Hi Markus, the build has been failing for a while it seems. I'm not sure about the cause, but on a hunch you might want to try and remove the .mvn/maven.config file, which configures the parallel build. That should at least make it easier to see the cause.

**Comment by fbarthez** [comment]
@hprange Henrique, are you fine with disabling the parallel build feature. It looks like it's causing the build to fail since a while. If so, should we do it in a separate PR?

**Comment by markusstoll** [comment]
did that, now it was building fine... strange

**Pull request merged**
