### PR TITLE
Update bcrypt implementation to version 0.4

### PR DESCRIPTION
**Pull request by fbarthez**
http://www.mindrot.org/projects/jBCrypt/news/rel04.html: "This corrects an integer overflow that occurs with very large log_rounds values, first reported by Marcus Rathsfeld."

### CODE REVIEW

**Comment by paulhoadley** [comment]
Hi Fabian,

Two quick questions, as I'm not familiar with the jBCrypt project, or the lineage of `BCrypt.java` in Wonder:

1. Is this ported directly over from jBCrypt with no changes?
2. Is it backwards compatible? More specifically, if I have an app deployed using Wonder's `BCrypt` with hashed passwords in a database, will `checkpw()` continue to return the expected results after this change?

(I assume the answers are "yes" and "yes", I just thought it was worth making it all explicit here.)

**Comment by fbarthez** [comment]
Hi Paul, yes and yes – to the best of my knowledge. Markus' question on the list made me look at the origin of wonder's bcrypt class.

**Comment by darkv** [comment]
The tests should go into ERXTest instead of ERXExtensions.

**Comment by fbarthez** [comment]
Which explains why there were no unit tests in ERExtensions and why Ramsey didn't add the test class in the first place. I did wonder about that…

**Comment by darkv** [comment]
The huge code base of Wonder can be confusing at times ;-)

**Pull request merged**
