### PR TITLE
Wonder 7 ant build pimping

### PR DESCRIPTION
**Pull request by darkv**
This updates the ant infrastructure to use Java 8 for compilation and cleans up / fixes the build files.

The ant commands

* ant clean
* ant frameworks
* ant applications
* ant examples
* ant deployment.tools
* ant docs
* ant dist

are running successfully. Please comment if any other changes should be added to this pull request.

### CODE REVIEW

**Comment by paulhoadley** [comment]
Nice work Johann.

**Comment by darkv** [comment]
I had no time to check if these lines in build.properties for applications are used anywhere or have any impact:

```embed.Local=true
embed.Network=true
embed.Project=true
embed.System=true
embed.User=true
```

At least in the ant files I did not see any reference. Any reason to keep them?

**Comment by paulhoadley** [comment]
An application’s `build.xml` will reference those in its invocation of the `woapplication` task:

```
  <frameworks root="ProjectLocal" embed="${embed.ProjectLocal}" eclipse="true" />
  <frameworks root="External" embed="${embed.External}" eclipse="true" />
  <frameworks root="Local" embed="${embed.Local}" eclipse="true" />
  <frameworks root="User" embed="${embed.User}" eclipse="true" />
  <frameworks root="System" embed="${embed.System}" eclipse="true" />
  <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
```

For example, in the not particularly up-to-date `master` branch of my fork right now:

```
$ git grep embed.Network
Examples/Ajax/MooToolsExample/build.xml:                  <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Examples/D2W/ERModernMoviesDemo/build.xml:                        <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Examples/ERJaxWS/WebService_Created/build.xml:                    <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Examples/ERJaxWS/WebService_Imported/build.xml:                   <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Examples/ERJaxWS/WebService_Stateful/build.xml:                   <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Examples/Misc/ERDistributionExampleClient/build.xml:                      <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Examples/Misc/ERPDFExamples/build.properties:embed.Network=true
Examples/Misc/ERPDFExamples/build.xml:                    <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Examples/Misc/ERWebSocketExample/build.xml:                       <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Examples/Misc/LuceneExample/build.xml:                    <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Examples/Misc/TextSearchDemo/build.xml:                   <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Tests/ERModernMoviesTest/build.xml:                       <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Tests/ERRestTest/build.xml:                       <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Tests/JavaNeo4JAdaptorTest/build.xml:                     <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Tests/PluginTest/build.xml:                       <frameworks root="Network" embed="${embed.Network}" eclipse="true" />
Tests/TestAdaptor/build.xml:                      <frameworks root="Network" embed="${embed.Network}" eclipse="true" />```

So I'd keep them.

**Comment by darkv** [comment]
Those build.xml files are replaced by the default Wonder build files with this pull request. Does not make sense that nearly all projects in Wonder use the files from Build/build/ but these exceptions you list use those from the WOLips templates. Within the Wonder build.xml files a quick search for "embed" reveals the following properties:

* wo.system.root.bundles.embed
* wo.external.root.bundles.embed
* wo.local.root.bundles.embed

So it seems that embed.Local, embed.User, … are only used for your own projects when using the WOLips project templates.

**Comment by paulhoadley** [comment]
Sounds good then.

**Pull request merged**
