### PR TITLE
Add collectors for NSCollection types

### PR DESCRIPTION
**Pull request by hprange**
This commit adds a new class `ERXCollectors`. It includes implementations of the `Collector` interface for various useful reduction operations related with NSCollection classes.

### CODE REVIEW

**Comment by paulhoadley** [comment]
Very nice Henrique.

**Comment by darkv** [comment]
This produces an error on Jenkins during test run:

> error: package org.hamcrest does not exist

**Comment by hprange** [comment]
Oh the Ant build! I will take a look. My bad.

**Comment by hprange** [comment]
@darkv I've committed the fix directly to `master`.  The problem should be fixed now. Let me know if something is still not working.

**Comment by darkv** [comment]
Looks good, thanks!

**Pull request merged**
