### PR TITLE
Added file selection button to ERDragAndDropUpload

### PR DESCRIPTION
**Pull request by frelin**
Added multiple file selection button to ERDragAndDropUpload, with the option to show a button or use the ID from an external button. The component can also be used without content to just show a button.

### CODE REVIEW

**Comment by paulhoadley** [comment]
Hi Fredrik,

This pull request for adding a button to `ERDragAndDropUpload` also contains commits touching `AjaxDatePicker` and a stray merge commit as well. Would you be able to re-submit this without those extraneous commits?

**Comment by frelin** [comment]
Yes, I saw that. It is from an old pull request I made 2012. I tried to reset the files to what is in Wonder now.

Sorry, I am not good with git.

Should i delete my branch in some way, re-fork and apply the changes again?

/Fredrik

**Comment by paulhoadley** [comment]
Ideally you need to have your proposed changes on a single feature branch, rebased against `upstream/master`, push to GitHub, then open the PR against _that_ branch. I'm not sure how you'll get there from where you are though. @darkv?

**Comment by chillatgvc** [comment]
Make a new branch from your fork of master and git cherry-pick your changes.

**Comment by paulhoadley** [comment]
Hi @frelin,

I don't think you can salvage this PR as it stands. What you could do is:

1. Create a branch from `upstream/master`: `git branch my-feature upstream/master; git checkout my-feature`.
2. Cherry pick the commits you want for this PR over to that feature branch: `git cherry-pick a6c4b42d`. (If there are other relevant commits, cherry pick those as well.)
3. Push that to a remote feature branch: `git push -u origin my-feature:my-feature`.
4. Open a new PR against _that_ branch.
5. Close this PR.

See how you go.

**Comment by frelin** [comment]
Hi,

I just closed the pull request after making a new one, which should be clean. I also included a fix from Michael Kondratov in the request.

/Fredrik

**Pull request closed without merging**
