### PR TITLE
Changes to make use of EOSchemaSynchronizationFactory

### PR DESCRIPTION
**Pull request by aacirino**
Changes to make use of EOSchemaSynchronizationFactory instead of deprecated and troubled EOSynchronizationFactory solves a series of SQL generation issues with different JDBC plug-ins (at least I tested with MySQL and FrontBase) and with migrations.

Also added some code to deal with fully qualified database (schema) and table names, like "ALTER TABLE "MyDatabaseSchema"."SomeTable" ..." when the fully qualified name is used as the table name in ERXMigrationTable newTableNamed(String name) for example.

### CODE REVIEW

**Comment by aacirino** [comment]
Sorry, I was in a hurry and didn't test well. Now seems to be fine.

**Comment by aacirino** [comment]
Should I merge the three commits and create a new pull request or leave as is?

**Comment by darkv** [comment]
Having several commits in a pull request is no problem.

**Comment by aacirino** [comment]
I discovered more issues with SQL and migrations generation that need more work. For example with FrontBase, SQL generator, as when used in Entity Modeler, will not generate indexes and will create the same PK for each subclassed entity (at least in single table inheritance). Also, migrations as when used in Entity Modeler, will not generate UNIQUE constraints nor DEFAULT for VARCHAR.

So I will close this pull request and come back when I am sure the issues have been solved and the frameworks are well tested.

**Comment by chillatgvc** [comment]
If I understand what you mean, "the same PK for each subclassed entity (at least in single table inheritance)" is not a bug, it is a requirement.  All objects in an EOF inheritance hierarchy need  to share a common PK as the EOGlobalId is the name of the base entity and the PK.  If they did not share the same PK sequence, chaos would result.

**Comment by aacirino** [comment]
Hi Chuck, see below what I mean. That's a SQL generated for a toy model I am using (sorry for the Portuguese) where the additional PK statements I mentioned are shown clearly. There are two pairs of SET UNIQUE and ALTER TABLE statements that needn't be there.

-- SQL creation time : 2015-05-13 19:52:55 Etc/GMT;

-- PlugIn version : 2.6.4;

-- To change any Structure Information this Command is must have;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;

DROP TABLE "Parte"."Parte" CASCADE;

COMMIT;


-- SQL creation time : 2015-05-13 19:52:55 Etc/GMT;

-- PlugIn version : 2.6.4;

-- To change any Structure Information this Command is must have;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;

-- The 'Drop Primary Key Support' option is unavailable.;

CREATE TABLE "Parte"."Parte" (
	"id" INTEGER NOT NULL,
	"idade" INTEGER DEFAULT 0 UNIQUE,
	"subClasse" VARCHAR(10) NOT NULL,
	"CNPJ" VARCHAR(16) DEFAULT 'XXX',
	"CPF" VARCHAR(16)
);

SET UNIQUE = 1000000 FOR "Parte"."Parte";

ALTER TABLE "Parte"."Parte" ALTER "id" SET DEFAULT UNIQUE;

SET UNIQUE = 1000000 FOR "Parte"."Parte";

ALTER TABLE "Parte"."Parte" ALTER "id" SET DEFAULT UNIQUE;

SET UNIQUE = 1000000 FOR "Parte"."Parte";

ALTER TABLE "Parte"."Parte" ALTER "id" SET DEFAULT UNIQUE;

ALTER TABLE "Parte"."Parte" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

COMMIT;

**Comment by chillatgvc** [comment]
Ah!  Yes, that is at least redundant.

**Pull request closed without merging**
